### ISSUE TITLE
How to tell if a DDS file is a cube map

### ISSUE THREAD

**Issue by ScanMountGoat** [SiegeEngine/ddsfile#10]
I can create cube maps by setting `is_cubemap` to `true` in `Dds::new_dxgi`. This works in all the applications I've tested so far (Photoshop, Paint.net, RenderDoc). I can also create a cube map by setting `is_cubemap` to `false` but setting six arrays. This opens as expected in Photoshop's DDS plugin and RenderDoc but not in paint.net. This seems reasonable since not all applications show mipmaps or arrays.

The main issue is when I save a cube map from either Photoshop or Paint.net. The resulting DDS has the cube map flag set to true, but the array count is 1. I couldn't find a way to tell if this flag is set from code other than to inspect the debug output of `Header10`.

**Comment by mikedilger** [comment]
I wrote this back in Jan 2018 and haven't used it recently. Your feedback with real world usage is really helpful.

It looks like we are doing it wrong, and probably because Microsoft mislead me:

According to the example in the Microsoft docs https://docs.microsoft.com/en-us/windows/win32/direct3ddds/dds-file-layout-for-cubic-environment-maps DXGI Cube Map would have array size of 6 with RESOURCE_MISC_TEXTURECUBE

but according to the spec https://docs.microsoft.com/en-us/windows/win32/direct3ddds/dds-header-dxt10 the array_size should be the number of cubes (since you can have an array of cubes), thus 1.

I'll push a fix.

**Comment by mikedilger** [comment]
Ok I pushed a fix (225cfd4ff7589afbc4373d4c5f1927b69122b6b0) [says ezicheq because I'm at work]

**Comment by ScanMountGoat** [comment]
Thanks for looking into this. On the latest commit, I now initialize my DDS files like this to get the appropriate number of layers and have applications tell that it's a cube map. Setting is_cube to false but keeping the 6 arrays also works but I don't get descriptive layer names like "X+", "Y-", etc in applications. This seems to work as expected.

I'm writing a texture format to DDS that specifies 6 layers for cube maps and 1 for a 2D texture with no arrays. Is `misc_flag` being private intentional? The original issue I was having is how to convert back to the number of layers when reading the DDS I generate with ddsfile.
```rust
let mut dds = Dds::new_dxgi(
    my_texture.height,
    my_texture.width,
    None,
    my_texture.image_format.into(),
    Some(my_texture.mip_count),
    Some(my_texture.layer_count), // this is 6 for cube maps for this format
    None,
    my_texture.layer_count == 6, // this can also be false now
    ddsfile::D3D10ResourceDimension::Texture2D,
    ddsfile::AlphaMode::Unknown,
)
.unwrap();

// When converting back to the texture file format, find the number of 2D layers.
// Doesn't compile since misc_flag is private.
let num_2d_layers = if dds.header10.unwrap().misc_flag == ddsfile::MiscFlag::TEXTURECUBE {
    dds.get_num_array_layers() * 6
} else {
    dds.get_num_array_layers()
};
```

**Comment by mikedilger** [comment]
No reason it was private, again looks like an oversight.  I pushed another commit to fix.

**Comment by mikedilger** [comment]
Once it's working for you I'll cut a new version

**Comment by ScanMountGoat** [comment]
I can confirm it's working now. A new version would be great.

**Comment by mikedilger** [comment]
0.5.0 is released

I fixed a bunch of clippy warnings, a typo in a constant, and made one breaking change:  new_dxgi() and new_d3d() take structured parameters (10 ordered parameters was just too much).

**Comment by curldivergence** [comment]
Hi! I'm also trying to load a DDS cubemap and face a similar issue: I'm creating a 1024x1024 BGRA8 cubemap via cmft (file size on disk is, reasonably, ~24 Mb), and I can tell the file contains a cubemap by inspecting `caps2`, but it seems I cannot actually access the data besides the 0th face: multiplying array layer count by 6 doesn't get me anywhere since the library still thinks it's equal to 1, so `Dds::get_data(0).unwrap().len()` call returns `4194304`, i.e. one 1024x1024 face, and `get_data({1,2,...})` calls fail with `OutOfBounds` error due to the check in `get_offset_and_size()`. 

So do I understand correctly that currently it's not possible to access all the faces, or I'm doing something wrong? :)

Thank you!

**Comment by curldivergence** [comment]
I did not dive into code too much, but looks like the simplest way to "fix" this is something like
```
@@ -314,6 +318,8 @@ impl Dds {
     pub fn get_num_array_layers(&self) -> u32 {
         if let Some(ref h10) = self.header10 {
             h10.array_size
+        } else if self.header.caps2.contains(Caps2::CUBEMAP) {
+            6
         } else {
             1 // just the 1 layer
         }
```
Of course, it does not account for cubemap arrays, but I'm not sure how to deal with such a case. Probably a cleaner fix would be to calculate face count from the raw data size in the absence of `header10`?

**Comment by mikedilger** [comment]
That seems reasonable. I pushed the change onto master.

**Comment by curldivergence** [comment]
Hm, did you? :) As far as I can see, the latest commit is from March 9th. Anyway, as I've mentioned above, I'm not sure if this change is clean enough to make it to master, so I'll give it a ride in my fork of this repo for now. Thanks!

**Comment by mikedilger** [comment]
Sorry, I had only pushed it to one of the three remotes where it is hosted.
